[project]
name = "advance-topic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.8",
    "notebook>=7.5.0",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "scrapy>=2.13.4",
]
